```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Hidden Libraries
library(knitr)  # For figures, tables and matricies
library(kableExtra)  # For kable matrix
library(pander)  # For more complex matricies symbol 
library(rmarkdown)
library(tidyverse)
```

# Fundamentals of Data Science Assessment Sheet

#### *Matt Prill*

Note: *All code formulated for this assessment is accessible in my github repository linked here. It also contains images of my hand written workings out. There is no onus to look at these; all relevant and neat workings can be seen in this document. I have included them in the repository so that I can* **(A)** *track my own workflow (version control) and* **(B)** *allow you to consult them should you wish to.*

## Question 1a

#### Initial Equations:

$$
\Large
\begin{aligned}
x + y + z &= 1 \\
x + 2y + 4z &= \eta \\
x + 4y + 10z &= \eta^2
\end{aligned}
$$\

#### Corresponding Coefficient Matrix:

$$
\Large
A = \begin{bmatrix}
1 & 1 & 1 \\
1 & 2 & 4 \\
1 & 4 & 10 
\end{bmatrix}
\begin{bmatrix}
1  \\
η  \\
η^2  
\end{bmatrix}
$$

#### Calculating the Determinant of A:

To showcase that these equations lack a unique solution for any value of η, I can attempt to find the determinant. To to find a determinant of square matrix (irrespective of size), I must;

1.  Pick a coefficient from the first row.
2.  Delete remaining elements in coefficient's respective row and column.
3.  Make a matrix of the remaining elements.
4.  Find the determinant of the sub-matrix, and multiply this with the coefficient.
5.  Repeat the same procedure for each element in the first row.
6.  To determine the sign of each term, sum the indices of the coefficient. If it is even, the sign is positive, and if it’s odd, the sign is negative.
7.  Sum all terms to find the determinant (Linear Algebra Slides, 2019).

Therefore, to find the determinant ($\text{det}$) of a $3 \times 3$ matrix, I can use the following formula:

$$
\Large
\text{det} \begin{bmatrix} a & b & c \\ d & e & f \\ g & h & i \end{bmatrix} = a \times \text{det} \begin{bmatrix} e & f \\ h & i \end{bmatrix} - b \times \text{det} \begin{bmatrix} d & f \\ g & i \end{bmatrix} + c \times \text{det} \begin{bmatrix} d & e \\ g & h \end{bmatrix}
$$

The terms are added/ subtracted depending on the sum the row and column indices of the coefficient. Even = positive. Odd = negative. For example "- b" is negative because b is $x_{12}$, thus the sum of the row and column indices $= 1+2 = 3 = odd$.

Applying this to the $3 \times 3$ matrix:

$$
\Large
A = \begin{bmatrix}
1 & 1 & 1 \\
1 & 2 & 4 \\
1 & 4 & 10 
\end{bmatrix}
=
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i 
\end{bmatrix}
$$

Thus,

$$
\Large
\text{det}(A) =
1 \times \text{det} \begin{bmatrix} 2 & 4 \\ 4 & 10 \end{bmatrix} - 1 \times \text{det} \begin{bmatrix} 1 & 4 \\ 1 & 10 \end{bmatrix} + 1 \times \text{det} \begin{bmatrix} 1 & 2 \\ 1 & 4 \end{bmatrix}
$$

To calculate the determinants of the $2 \times 2$ matrices, I can apply the formula:

$$
\Large
\text{det}\begin{bmatrix} a & b \\ c & d \end{bmatrix} = ad - bc
$$ Corresponding calculations for determinants of the $2 \times 2$ matrices:

$$
\Large
\text{det} 
 \begin{bmatrix} 2 & 4 \\ 4 & 10 \end{bmatrix} = 20 - 16 =\mathbf{4}
$$

$$
\Large
 \text{det} \begin{bmatrix} 1 & 4 \\ 1 & 10 \end{bmatrix} = 10 - 4 =\mathbf{6}
$$

$$
\Large
 \text{det} \begin{bmatrix} 1 & 2 \\ 1 & 4 \end{bmatrix} = 4-2 = \mathbf{2}
$$

Substituting these determinants into the aforementioned $3 \times 3$ matrix determinant formula gives:

$$
\Large
\text{det}(A)=
(1 \times 4)  - (1 \times 6) + (1 \times 2) = \mathbf{0}
$$

The determinant of the coefficient matrix and therefore the matrix vector is $0$. This means that the matrix is singular:

$$
\Large
\text{det}(A) = Ax = 0
$$\

In being singular, the matrix does not have an inverse meaning that the corresponding linear equations have either no, or unlimited solutions. Regardless, in this case, the initial equations have no unique solution for $η$.

\
\
\
\

## Question 1b

#### The Set of Linear Equations:

$$
\Large
\begin{aligned}
x + y + z &= 1 \\
x + 2y + 4z &= \eta \\
x + 4y + 10z &= \eta^2
\end{aligned}
$$\

#### The Corresponding Augmented Matrix:

$$
\Large
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 1 \\
1 & 2 & 4 & \eta \\
1 & 4 & 10 & \eta^2
\end{array}
\right]
$$

#### Using Gaussian Elimination to Identify the Solutions for η:

1.  $$\Large
    (\text{Row }2) -1 \times (1) = 
    \left[
    \begin{array}{ccc|c}
    1 & 1 & 1 & 1 \\
    0 & 1 & 3 & \eta-1 \\
    1 & 4 & 10 & \eta^2
    \end{array}
    \right]
    $$

2.  $$\Large
     (\text{Row } 3) -1 \times (1) = 
    \left[
    \begin{array}{ccc|c}
    1 & 1 & 1 & 1 \\
    0 & 1 & 3 & \eta-1 \\
    0 & 3 & 9 & \eta^2-1
    \end{array}
    \right]
    $$

3.  $$\Large
    (\text{Row }3) -3 \times (2) = 
    \left[
    \begin{array}{ccc|c}
    1 & 1 & 1 & 1 \\
    0 & 1 & 3 & \eta-1 \\
    0 & 0 & 0 & \eta^2-3\eta +2
    \end{array}
    \right]
    $$\

The equation corresponding to the bottom row of the augmented matrix is 0. It is also a quadratic equation where:

$$
\Large
\eta^2-3\eta +2
= ax^2 + bx + c = 0
$$

Now, I can either factorise:

$$
\Large
\eta^2-3\eta +2=
(\eta-1)(\eta-2)= 0
$$

Or alternatively, I can use the quadratic formula to derive the solutions for $\eta$:

$$
\Large
\eta = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
 = \frac{-(-3) \pm \sqrt{-3^2 - 4\times1\times2}}{2\times1}
 = 1 \text{ or } 2
$$

\

$$
\Large
\eta = 1 \text{ or } 2
$$

\

#### Characterising the equations for both solutions:

##### Where $\eta = 1$:

$$
\Large
\begin{aligned}
x + y + z &= 1 \\
x + 2y + 4z &= 1 \\
x + 4y + 10z &= 1^2
\end{aligned}
$$

Corresponding augmented matrix:

$$
\Large
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 1 \\
0 & 1 & 3 & 1-1 \\
0 & 0 & 0 & 1^2-3(1)\ + 2
\end{array}
\right]
\Large
= 
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 1 \\
0 & 1 & 3 & 0 \\
0 & 0 & 0 & 0\ 
\end{array}
\right]
$$

Thus, when $\eta = 1$:

$$
\Large
\begin{aligned}
x + y + z &= 1 \\
y + 3z & = 0 \\
\end{aligned}
$$

## ?Now I can assign the free variable (z) to a parameter and characterise ?

\
\
\

##### Where $\eta = 2$:

$$
\Large
\begin{aligned}
x + y + z &= 1 \\
x + 2y + 4z &= 2 \\
x + 4y + 10z &= 2^2
\end{aligned}
$$

Corresponding augmented matrix:

$$
\Large
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 1 \\
0 & 1 & 3 & 2-1 \\
0 & 0 & 0 & 2^2-3(2)\ + 2
\end{array}
\right]
\Large
= 
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 1 \\
0 & 1 & 3 & 1 \\
0 & 0 & 0 & 0\ 
\end{array}
\right]
$$

Thus when $\eta = 2$:

$$
\Large
\begin{aligned}
x + y + z &= 1 \\
y + 3z & = 1 \\
\end{aligned}
$$

## ?Now I can assign the free variable (z) to a parameter and characterise?

\
\
\
\
\
\

## Question 2a

$P_{1} = P(\text{Alice winning when first to throw})$

The distribution shares some characteristics of the Bernoulli distribution whereby there are two outcomes (success & failure) and discrete. However, the question is asking for the probability to a given success. The balls are thrown (trials) until a success (hit). Furthermore, I have to assume that each throw is independent of the other which makes the distribution memoryless with two outcomes: success (win), & failure (miss). This is a geometric distribution.

$$
\large
\left.
\begin{aligned}
\text{Hit} = α\\
\text{Miss}= 1-α\
\end{aligned}
\right\} \text{Alice}
$$

$$
\large
\left.
\begin{aligned}
\text{Hit} =  β\\
\text{Miss}= 1- β\
\end{aligned}
\right\} \text{Ben}
$$

#### The probability of Alice missing Ben with her first throw and going on to win:

P(Alice misses first throw) = $1 - α$

P(Ben misses first throw) = $1-β$

Thus,\
P(Alice miss, Ben miss) = $(1 - α)\times (1-β)$

So,\
P(Alice miss, Ben miss, Alice goes onto win) = $P_{1}\times(1 - α) \times(1 - β)$

$P_{1}$ is able to be used here because of the memoryless nature of the geometric distribution; no matter how many trials have transpired prior to a given throw of Alice's, the probability that she will win from that point onwards is still $P_{1}$.

\
\

## Question 2b

Because I'm working with the Geometric distribution with parameter p, X has a probability mass function:

$$
\large
P(X = k) = p(k) =
\left\{
\begin{aligned}
(1 − p)^{k-1}p,\\
0\
\end{aligned}
\right.
$$

This is not conditional probability as the probability is with respect to the beginning of the round.

As discussed, the probability that Alice and Ben both miss in a given round is: $(1 - α)\times (1-β)$

\
This could repeat n times where n can denotes any integer (theoretically): $((1 - α)\times (1-β))^n$ meaning the probability will be a summation of all the rounds where n is potentially indefinite $(\sum_{n=1}^{\infty})$

\
Eventual success from Alice (given that she throws first) therefore gives: $$
\Large
P(X = n) =  \sum_{n=1}^{\infty} ((1 - α)\times (1-β))^{n-1} \timesα
$$\

The $n-1$ term is used because Alice and Ben must miss every time until the final round (hence $-1$); the $n$-th round is the one she wins (success).

The $α$ term is therefore added as it still denotes the probability that she will hit successfully.

\
Therefore, substituting my terms in gives:

$$
\Large
P_{1} =  \sum_{n=1}^{\infty} ((1-α)\times(1-β))^{n-1}\times α
$$

In line with the geometric series, this is then equivalent to: $$
\Large
P_{1} =
α\times \sum_{n=0}^{\infty} ((1-α)\times(1-β))^{n}
$$ This holds even if n = 0 because in this instance the equation would still equate to α.\
\

In the infinite geometric series equation $\sum_{n=0}^{\infty}r^n=\frac{1}{1-r}$ where $|r|< 1$\
$(1-α)\times(1-β)$ is the common ratio (this holds because the terms are probabilities and so \< 1) Thus:

$$
\Large 
r = (1-α)\times(1-β)
$$\
\

Finally, substituting the values into the geometric series equation gives: $$
\Large
P_{1} = α \times \frac{1}{1-(1-α)\times(1-β)}
$$

## Question 2c

For Ben to throw go first but Alice still to win, there must be $1-β$ term.

However given the order of throws, the point at which Alice wins must be preceded by a miss from Ben $(1-β)$ after which she can throw (and win). Therefore,

$$
\Large 
P2 \neq \sum_{n=1}^{\infty} ((1-β) \times (1-α))^{n-1} \times α
$$

Instead there must be a final $1-β$ before Alice is victorious. Again, the $n$-th round is the one where she wins (also the round where Ben misses a final time) Thus,

$$
\Large 
P_{2} = \sum_{n=1}^{\infty} ((1-β) \times (1-α))^{n-1} \times (1-β) \times α 
$$

By applying the geometric series steps as in the previous question, we get that: $$
\Large 
P_{2} = (1-β) \times α \times \sum_{n=0}^{\infty} ((1-β) \times (1-α))^{n}
$$ And finally:

$$
\Large
P_{1} = (1-β)\timesα \times \frac{1}{1-(1-α)\times(1-β)}
$$\
\
\
\

## Question 3a

The tins' weight follows a normal distribution $μ = 426, σ = 21$. The variance (Var) is therefore $441$ because var$= σ^2$.

Infinite geometric series for $|r| < 1$:\
$$
\Large 
\sum_{n=0}^{\infty}r^n=\frac{1}{1-r} 
$$\

The equation $\Large \sum_{n=0}^{\infty}n(n-1)r^{n-2}$ has no common ratio i.e. there are extra terms: $n(n-1)$ - a polynomial.This means it is not part of the geometric series but we can use properties of the geometric to work out the sum of the latter.

1.Differentiating the geometric series gives a similar form to the second expression:

$$
\Large
\frac{d}{dr} \left( \sum_{n=0}^{\infty} r^n \right) = \frac{d}{dx} \left( \frac{1}{1 - r} \right)
$$

For the first term (equation) I apply the power rule: $\frac{d}{dx} \left( x^n \right) = n x^{n-1}$ Note, I am derivating wiht respect to r i.e. r = x to match geometric series form.

$$
\Large
\frac{d}{dx} \left( \sum_{n=0}^{\infty} r^n \right) =
\sum_{n=0}^{\infty} nr^{n-1}
$$

And for the sum I can apply the quotient rule to find the derivative: $\frac{d}{dx} \left( \frac{f}{g} \right) = \frac{g \frac{d}{dx}(f) - f \frac{d}{dx}(g)}{g^2}$ Again, I am derivating with respect to r.

$$
\Large
 \frac{d}{dx} \left( \frac{1}{1 - r} \right) = \frac{(1-r)\times\frac{d}{dx}(1)-1 \times \frac{d}{dx}(1-r)}{(1-r)^2}
 = \frac{1}{(1-r)^2}
$$
Now I have:


$$
\Large
\sum_{n=0}^{\infty} nr^{n-1} = \frac{1}{(1-r)^2}
$$

The equation form now mirrors that of the equation of interest:
$$
\Large 
\sum_{n=0}^{\infty}n(n-1)r^{n-2}
$$

#### Finding Expression for:



\
\
\



\
\
\

## Question 3b

The expectation of each fine (E[Fine])...

\
\
\
\## References

Linear Algebra Slides, 2020
